language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes pip numpy cython astropy setuptools pillow
  - pip install --use-mirrors pytest coveralls pytest-cov
  - pip install --upgrade pillow
  - python setup.py build_ext --inplace
  - python setup.py build

script:
  - py.test --cov toasty toasty

after_success:
  - coveralls
